services:
#  workfolio-service:
#    image: workfolio-server:local
#    container_name: workfolio-server
#    ports:
#      - "8080:8080"
#    env_file:
#      - docker-compose.env
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
#    networks:
#      - workfolio-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./docker-compose.env
    environment:
      MYSQL_DATABASE: workfolio
      MYSQL_USER: spectrum
      MYSQL_PASSWORD: "123456789a"
      MYSQL_ROOT_PASSWORD: "123456789a"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command:
      - mysqld
      - --max_connections=100
      - --innodb_buffer_pool_size=256M
      - --innodb_log_file_size=64M
      - --innodb_flush_log_at_trx_commit=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - workfolio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:8.2.0-alpine
    container_name: redis
    env_file:
      - docker-compose.env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes --save 900 1 --save 300 10 --save 60 10000
    networks:
      - workfolio-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - "9090:9090"
#    networks:
#      - workfolio-network
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    networks:
#      - workfolio-network

volumes:
  mysql-data:
  redis-data:

networks:
  workfolio-network:
    driver: bridge
