package com.spectrum.workfolio.domain.enums

enum class MsgKOR(val message: String) {
    NOT_EXIST_EMAIL("존재하지 않는 이메일입니다."),
    DUPLICATION_EMAIL("중복 된 이메일입니다."),
    NOT_FOUND_WORKER("존재하지 않는 유저입니다."),
    NOT_FOUND_RECORD("존재하지 않는 레코드입니다."),
    NOT_FOUND_RECORD_GROUP("존재하지 않는 레코드 그룹입니다."),
    NOT_FOUND_CAREER("존재하지 않는 회사입니다."),
    NOT_FOUND_SALARY("존재하지 않는 급여입니다."),
    NOT_FOUND_PROJECT("존재하지 않는 프로젝트입니다."),
    NOT_FOUND_ACTIVATE("존재하지 않는 활동입니다."),
    NOT_FOUND_ATTACHMENT("존재하지 않는 첨부입니다."),
    NOT_FOUND_MEMO("존재하지 않는 메모입니다."),
    NOT_FOUND_LANGUAGE_SKILL("존재하지 않는 어학입니다."),
    NOT_FOUND_LANGUAGE_TEST("존재하지 않는 어학 시험입니다."),
    NOT_FOUND_EDUCATION("존재하지 않는 교육입니다."),
    NOT_FOUND_WORKER_RECORD_GROUP("존재하지 않는 레코드 참여 이력입니다."),
    NOT_FOUND_RESUME("존재하지 않는 이력서입니다."),
    NOT_FOUND_TURN_OVER_GOAL("존재하지 않는 목표입니다."),
    NOT_FOUND_INTERVIEW_QUESTION("존재하지 않는 면접 질문입니다."),
    NOT_FOUND_SELF_INTRODUCTION("존재하지 않는 자기 소개입니다."),
    NOT_FOUND_CHECK_LIST("존재하지 않는 체크리스트입니다."),
    NOT_FOUND_TURN_OVER_CHALLENGE("존재하지 않는 도전입니다."),
    NOT_FOUND_JOB_APPLICATION("존재하지 않는 지원 기록입니다."),
    NOT_FOUND_APPLICATION_STAGE("존재하지 않는 채용 절차입니다."),
    NOT_FOUND_TURN_OVER("존재하지 않는 이직입니다."),
    NOT_FOUND_TURN_OVER_RETROSPECTIVE("존재하지 않는 회고입니다."),
    NOT_FOUND_SYSTEM_CONFIG("존재하지 않는 설정입니다."),
    NOT_OWNER_RECORD_GROUP("레코드 그룹의 소유주가 아닙니다."),
    ALREADY_EXIST_WORKER_NICK_NAME("현재 닉네임과 동일합니다."),
    ALREADY_EXIST_WORKER_RECORD_GROUP("레코드 그룹에 이미 존재하는 멤버입니다."),
    NOT_MATCH_RECORD_OWNER("레코드의 소유자가 아닙니다."),
    NOT_MATCH_RECORD_GROUP_OWNER("레코드 그룹의 소유자가 아닙니다."),
    NOT_MATCH_RECORD_GROUP_EDITOR("레코드 그룹의 에디터가 아닙니다."),
    CANNOT_DELETED_DEFAULT_RECORD_GROUP("기본 레코드 그룹은 삭제할수 없습니다."),
    INVALID_JWT_TOKEN("유효하지 않은 토큰입니다."),
    EXPIRED_JWT_TOKEN("만료된 JWT 토큰입니다."),
    UNSUPPORTED_JWT_TOKEN("지원하지 않는 JWT 토큰입니다."),
    MISSING_JWT_CLAIMS_TOKEN("정보가 부족한 JWT 토큰입니다."),
    MISSING_JWT_TOKEN("존재하지 않는 JWT 토큰입니다."),
    NOT_EXISTS_REFRESH_TOKEN("Refresh 토큰이 존재하지 않습니다."),
    INVALID_REFRESH_TOKEN_NOT_EXISTS("유효하지 않은 Refresh 토큰입니다."),
    INSUFFICIENT_PERMISSION("권한이 부족합니다."),
}
