build:
    maxIssues: 0

config:
    validation: true
    warningsAsErrors: true

output-reports:
    active: true
    exclude:
        - 'TxtOutputReport'
        - 'XmlOutputReport'

complexity:
    active: true
    ComplexCondition:
        active: true
        threshold: 10
    ComplexInterface:
        active: false
        threshold: 10
        includeStaticDeclarations: false
        includePrivateDeclarations: false
    CyclomaticComplexMethod:
        active: true
        threshold: 200
        ignoreSingleWhenExpression: false
        ignoreSimpleWhenEntries: false
        ignoreNestingFunctions: false
        nestingFunctions:
            - 'also'
            - 'apply'
            - 'forEach'
            - 'isNotNull'
            - 'ifNull'
            - 'let'
            - 'run'
            - 'use'
            - 'with'
    LargeClass:
        active: true
        threshold: 20000
    LongMethod:
        active: true
        threshold: 13000
    LongParameterList:
        active: true
        functionThreshold: 40
        constructorThreshold: 40
        ignoreDefaultParameters: false
        ignoreDataClasses: true
    NestedBlockDepth:
        active: true
        threshold: 10
    TooManyFunctions:
        active: true
        thresholdInFiles: 50
        thresholdInClasses: 50
        thresholdInInterfaces: 50
        thresholdInObjects: 50
        thresholdInEnums: 5
        ignoreDeprecated: true
        ignorePrivate: true
        ignoreOverridden: false

coroutines:
    active: true
    GlobalCoroutineUsage:
        active: true
    RedundantSuspendModifier:
        active: true
    SleepInsteadOfDelay:
        active: true
    SuspendFunWithFlowReturnType:
        active: true

empty-blocks:
    active: true
    EmptyClassBlock:
        active: false
    EmptyFunctionBlock:
        active: false
    EmptyKtFile:
        active: false

naming:
    active: true
    BooleanPropertyNaming:
        active: true
    NonBooleanPropertyPrefixedWithIs:
        active: true

performance:
    active: true
    SpreadOperator:
        active: false

potential-bugs:
    active: true
    HasPlatformType:
        active: true

style:
    active: false

libraries:
    LibraryEntitiesShouldNotBePublic:
        active: false
    ForbiddenPublicDataClass:
        active: false

exceptions:
    active: true
    TooGenericExceptionCaught:
        active: false
    TooGenericExceptionThrown:
        active: false
    SwallowedException:
        active: false

formatting:
    MaximumLineLength:
        active: false
